#!/usr/bin/env bash
# displays listening ports:
    # shows listening sockets only.
    # shows the PID and name of the program and, to which each socket belongs.

sudo netstat --listening --programs
